### ISSUE TITLE
Method to sort function parameters for EdgeStore

### ISSUE THREAD

**Issue by wshayes** [belbio/bel_lang#10]
Input: AST

Return: AST

Need to sort the optional function parameters and for parameters that are Functions or Modifiers that have multiple=true - sort their values.  

This is required to provide a consistently unique BEL statement for use in the EdgeStore - otherwise the same BEL Statement might show up multiple times with different parameter orderings in the EdgeStore.

This should probably work on the AST and then regenerate the BEL Statement string from the AST.

**Comment by davidchen** [comment]
suggestion for order of sorting:

1. required parameters by order defined in signature
     1. if a required parameter has multiples, sort them alphabetically by function name before entity/string value
2. optional parameters are not ordered - sort lexicographically?

**Comment by wshayes** [comment]
This is tightly related to #11 - the canonicalization issue.

**Comment by wshayes** [comment]
This issue was moved to belbio/bel#13
