### ISSUE TITLE
Orthologization method

### ISSUE THREAD

**Issue by wshayes** [belbio/bel_lang#13]
Input: AST
Input: species (singular)
Input: canonical=False
Input: partial=False
Return: AST

Orthologize each Entity that represents a Gene, mRNA, microRNA, or Protein if all entities can be orthologized to the given species. 

Canonicalize if canonical=True (e.g. for sending to EdgeStore), otherwise, use preferred Namespaces as opposed to Canonical Namespaces (should we provide these as part of the request?)

partial=False - refers to allowing partially orthologized statements - default False, if True - it would allow partial orthologization as oppose to requiring all relevant entities to be orthologized else revert all changes if only some of the given Entities can be orthologized.  

This will use the TermStore API to retrieve Orthologized Entities.

**Comment by davidchen** [comment]
If possible, could I get some examples? And why would canonicalization be optional?

**Comment by wshayes** [comment]
Provide orthology api via BEL API and an example BEL Statement orthologiziation.
