### ISSUE TITLE
Add examples to BEL YAML file

### ISSUE THREAD

**Issue by wshayes** [belbio/bel_lang#29]
For each of the function signatures and computed edge signatures, we should add an example BEL statement list:

    examples:
    - p(HGNC:F2) increases sec(p(HGNC:VWF))

**Comment by davidchen** [comment]
Would this go directly in as a comment in the YAML or as part of an "example" attribute of each signature? Or should these be in the wiki?

**Comment by davidchen** [comment]
If we simply have an "examples" list, it may be hard to tell which example is supposed to represent which signature.

**Comment by wshayes** [comment]
Each example should be associated with a specific function or computed edge signature.  This isn't urgent.

**Comment by wshayes** [comment]
This issue was moved to belbio/bel#12
