### ISSUE TITLE
Add process flow diagram to root readme

### ISSUE THREAD

**Issue by adifabio** [belbio/bel_lang#3]

**Comment by wshayes** [comment]
What do you mean by a process flow diagram for bel.py? BEL statement -> parse -> AST?  I'm a bit confused.

**Comment by adifabio** [comment]
similar to what we have for the Pipeline
![0](https://user-images.githubusercontent.com/3788351/27975811-e5d34920-6331-11e7-9cd7-d9001ee30ad2.png)

**Comment by wshayes** [comment]
This issue was moved to belbio/bel#17
