### ISSUE TITLE
BEL -> BELglish?/BEnglish?

### ISSUE THREAD

**Issue by wshayes** [belbio/bel_lang#41]
Convert BEL statement into an English like version.   Use https://github.com/OpenBEL/openbel-contributions/blob/master/misc-scripts/openbel-bel2english.py as a starting point.  Goal is to transform BEL AST into an English-like version of BEL.

**Comment by davidchen** [comment]
@wshayes Will this be a function of our BEL object such as parse(), canonicalize(), etc.? Or does this go into dev tools?

**Comment by davidchen** [comment]
Also, should we keep data about the English-equivalent in the YAML? (EXAMPLE: `'act': 'molecular activity of the'` dictionary value... where does this go?)

**Comment by wshayes** [comment]
Let's create this as a separate file from the BEL Specification file - it should still be versioned the same as the BEL Specification.  

It should be a method on the BEL object, but put the main code in a separate module file, e.g. belglish.py.

**Comment by wshayes** [comment]
This issue was moved to belbio/bel#11
