### ISSUE TITLE
Mis-matched quote

### ISSUE THREAD

**Issue by wshayes** [belbio/bel_lang#42]
po = bel.parse("p(HGNC:AKT1) increases p('HGNC:EGF)")

Doesn't respond with an error of a mis-matched quote or indicate that single-quotes are not allowed.

**Comment by davidchen** [comment]
Given: `statement_to_parse = 'p(HGNC:AKT1) increases p(\'HGNC:EGF\')'`
Result: `bel_lang.exceptions.InvalidCharacter: Single quotes are not allowed! Please use double quotes.`

Given: `statement_to_parse = 'p(HGNC:AKT1) increases p("HGNC:EGF)'`
Result: `bel_lang.exceptions.MissingQuotation: Missing quotation mark somewhere!`
