### ISSUE TITLE
Clean up naming in EBNF/parser.py

### ISSUE THREAD

**Issue by wshayes** [belbio/bel_lang#58]
Inconsistent naming carries through into resulting ast_dict.

Change nspace -> ns
Change m_function -> modifier
Change m_function_args -> modifier_args

Related to #57

**Comment by davidchen** [comment]
This requires the changing of the Jinja template, and then a regeneration of an updated EBNF via yaml_to_ebnf.py

**Comment by davidchen** [comment]
Finished under https://github.com/belbio/bel_lang/commit/355adcd442138d8443fa9a6464f6e2f800d326e2.
