### ISSUE TITLE
bel_specification.py: Autocorrect to the highest version of each major, minor, patch available.

### ISSUE THREAD

**Issue by davidchen** [belbio/bel_lang#66]
For example: if 2.0.5 and 2.1.22 exists, then a user entering 2 will auto-correct to 2.1.22 and a user entering 2.0 will auto-correct 2.0.5.

**Comment by davidchen** [comment]
Related: Before auto-correcting can happen we'll need to implement a regex exp. to gather major, minor, patch, etc. from user entered string. Will help in error notification.

**Comment by wshayes** [comment]
Of course there are several python modules providing support for this:
* https://python-semanticversion.readthedocs.io/en/latest/
* https://github.com/k-bx/python-semver
* https://pypi.python.org/pypi/semver
* https://python-semanticversion.readthedocs.io/en/v1.0.0/

We may want to use prerelease and build identifiers at some point for versions that are being developed so would be nice to support that. Review the modules and select the best one for our needs (function, support, popularity, ...)

**Comment by davidchen** [comment]
Links 1 & 4 and 2 & 3 are duplicates. Reviewing both semver libraries now.

**Comment by davidchen** [comment]
Libraries did not provide sufficient functionality to automatically help us select the next highest available version given a wanted version and list of available versions. Implemented under https://github.com/belbio/bel_lang/commit/74edc89dabc825d260a2e865ccd52eb11b353e8d.

**Comment by wshayes** [comment]
I didn't see any tests added.  I was looking for them to better understand what you did.  Looks like you jump from Version 1 to 2 as an autocorrection which should not happen.

**Comment by davidchen** [comment]
Pytests added under https://github.com/belbio/bel_lang/commit/5fbbde1cec962c8e5687bacfca0ee107ae63507c. Please review.

**Comment by davidchen** [comment]
Corrections to _default_to_version() and corresponding pytests under https://github.com/belbio/bel_lang/commit/698fbf3d2e03f59ecea69e14bb335e28585d99f6. Please review and close.
